# [Notes]: https://www.jb51.cc/bash/387746.html
#        -A: to make NAMEs associative arrays (like hash table)
#        -g: When used in a function, `declare' makes NAMEs local, as with the `local'
#            command.  The `-g' option suppresses this behavior.
#
# [wb]: Currently the virtual env is outside the container. 
#       Or we can use the virtual env inside the container by "export MYVENV_PATH=/opt/myvenv"

declare -gA ENV
ENV[exec]=singularity
ENV[cont]=juliaPyFlex.simg
ENV[julia_depot]=.julia
ENV[env]=venv
ENV[mounts]=""

declare -gA PATHS
PATHS[JULIA_DEPOT_PATH]="${PWD}/${ENV[julia_depot]}"
PATHS[JULIA_PROJECT]="${PWD}"
PATHS[PYTHON]="${PWD}/${ENV[env]}/bin/python3.6"
PATHS[PYCALL_JL_RUNTIME_PYTHON]="${PWD}/${ENV[env]}/bin/python3.6"