############################################################################
# Script Name                : flexConfig.yml
# Description                : Set FleX simulation paras
# Date                       : 03/08/2020
# Contact                    : wenyan.bi@yale.edu
############################################################################

shear_stiffness: 0.125 
stretch_stiffness: 0.125 
drag: 0.1                     
lift: 0.1               
dynamic_friction: 0.5 
static_friction: 1.1
steps: 2 
substeps: 17
subiters: 80
extra_cp_spacing: 0.0
extra_cp_rad_mult: 1.0